### ISSUE TITLE
   hs.eventtap.event.newMouseEvent({hs.eventtap.event.types.leftMouseDragged}, { 10, 10 })

### ISSUE THREAD

**Issue by joyspce** [asmagill/hammerspoon-config#4]
hs.eventtap.event.newMouseEvent({hs.eventtap.event.types.leftMouseDragged}, { 10, 10 })
    hs.timer.usleep(1000);
    hs.eventtap.event.newMouseEvent({hs.eventtap.event.types.rightMouseUp}, { 10, 10 })
2017-04-24 07:49:14: Error: unrecognised mouse button eventtype: table: 0x610000c6d700

hello, dear author, why do I use this code, alway get that error? please help

**Comment by asmagill** [comment]
Sorry for missing this for so long.. I'm archiving the repository now; if you still have an issue, you're likely to get a faster response by posting an issue at https://github.com/Hammerspoon/hammerspoon/issues.
