### ISSUE TITLE
Load javascript from file://

### ISSUE THREAD

**Issue by markwu** [asmagill/hammerspoon-config#5]
Hi asmagill:

It that possible to load javascript from local storage like `<script src="file://abc/def/ghi/jkl.js"></script>` instead of local web server?

I try to figure it out, but no lucks. :(

https://github.com/asmagill/hammerspoon-config/blob/bf186c7636c73eaab43467711712c6191c274320/utils/_keys/cheatsheet.lua#L232

**Comment by asmagill** [comment]
I just tried it myself and apparently not... I think I remember reading somewhere that Safari can't read `file:` urls that are embedded in links, and `hs.webview` uses `WKWebView` which is the same base class that Safari uses for rendering web pages (can't find where I read that now, though, so if someone else can confirm/reject my memory, feel free to chime in)...

I'll push a version shortly that uses `hs.webview.usercontent` to inject the javascript into the view instead, just modify line 242 with the path to the `isotope.pkgd.min.js` file if you've put it somewhere else.

**Comment by asmagill** [comment]
Need to clean up my old config dir as I generally don't update it anymore -- see the latest version I just pushed at https://github.com/asmagill/hammerspoon-config-take2/blob/master/utils/_keys/cheatsheet.lua which uses script injection to bypass the need for a local web server.

**Comment by markwu** [comment]
@asmagill Thanks for your help, I already follow your method and load javascript from local directory through `webview.usercontent`.
